# Install pre-commit hooks via:
# pre-commit install

# yapf = yet another python formatter
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]

- repo: local
  hooks:
  # prospector: collection of linters
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector

  - id: version-number
    name: Check version numbers
    entry: python ./.github/check_version.py
    language: system
    files: '^(setup.json)|({{cookiecutter.module_name}}/__init__.py)'
