repos:
- repo: local
  hooks:
  - id: format
    name: format
    entry: hatch fmt -f
    language: system
    types: [python]
  - id: lint
    name: lint
    entry: hatch fmt -l
    language: system
    types: [python]
