# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
- master

jobs:
- job: test
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
    maxParallel: 4
  steps:
  # - template: .ci/azure-templates/apt-steps.yml
  - template: .ci/azure-templates/conda-steps.yml
  - template: .ci/azure-templates/pip-steps.yml

  - script: py.test --junitxml=test-results.xml --cov aiida_zeopp --cov-append .
    displayName: 'Run pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: docs
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
    maxParallel: 4
  variables:
    READTHEDOCS: 'True'
  steps:
  - template: .ci/azure-templates/pip-steps.yml
  - script: cd docs; make
    displayName: 'Make docs'

- job: pre_commit
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
    maxParallel: 4
  steps:
  - template: .ci/azure-templates/pip-steps.yml
  - script: pre-commit install; pre-commit run --all-files || ( git status --short; git diff ; exit 1 );
    displayName: 'Run pre-commit check'

#- job: coveralls
#  dependsOn:
#    - test
#  steps:
#  - task: UsePythonVersion@0
#    inputs:
#      versionSpec: '3.6'
#      architecture: 'x64'
#
#  - script: pip install coveralls
#    displayName: 'install coveralls'
#
#  - script: coveralls
#    displayName: 'Upload test coverage to coveralls.io'

# - job: 'Publish'
#   dependsOn:
#   - test
#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.x'
#       architecture: 'x64'
#   - script: python setup.py sdist
#     displayName: 'Build sdist'
