name: Publish on PyPI

on:
  push:
    tags:
      # After vMajor.Minor.Patch _anything_ is allowed (without "/") !
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == '{{ cookiecutter.github_user }}/{{ cookiecutter.repo_name }}' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch~=1.12.0

    - name: Build and publish
      run: |
        hatch publish
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH:  ${{ '{{ secrets.pypi_token }}' }}
